"""`doc-marshal index`: generate the docs index from the `type:` and `summary:` of every note.

This command owns the index end to end: it is overwritten on every run and must never be edited by
hand. A hand-maintained index is a document whose only job is to agree with the filesystem, and it
stops doing that the first time someone forgets a line.

    doc-marshal index
    doc-marshal index --check   # report whether the index is out of date

A note missing `type:` or `summary:` is an error, not a gap to render around -- the index would
silently under-describe the docs. Nothing is written until every note declares both.

The output carries no generation date on purpose: a timestamp would make `--check` fail on the day
after a run, with no content change, which trains everyone to regenerate noise.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote

from .config import load_registry
from .ontology import Registry
from .paths import find_docs_root, iter_notes, read_meta

HEADER = "<!-- generated by doc-marshal -- do not edit by hand -->"


def plural(count: int) -> str:
    """"1 note" rather than "1 notes" -- the index is read at the top of every session."""
    return "note" if count == 1 else "notes"


@dataclass(frozen=True)
class Note:
    path: Path  # relative to the docs root
    doc_type: str
    summary: str


def collect(docs_root: Path, registry: Registry) -> tuple[list[Note], list[str]]:
    """Return (notes, problems). Problems are notes that cannot be indexed."""
    notes: list[Note] = []
    problems: list[str] = []
    for path in iter_notes(docs_root, registry.settings):
        rel = path.relative_to(docs_root)
        meta, _, error = read_meta(path)
        if error is not None:
            problems.append(f"{rel}: {error}")
            continue
        assert meta is not None
        doc_type = meta.get("type")
        summary = meta.get("summary")
        missing = [
            name
            for name, value in (("type", doc_type), ("summary", summary))
            if not isinstance(value, str) or not value.strip()
        ]
        if missing:
            problems.append(f"{rel}: missing {' and '.join(missing)}")
            continue
        if registry.get(doc_type) is None:
            # The index names each note's type, so one outside the ontology would be published as
            # though it were real. The validator errors on this too; refusing here keeps the two
            # from disagreeing about what a note is.
            problems.append(f"{rel}: type {doc_type!r} is not one of {sorted(registry.enabled)}")
            continue
        assert isinstance(doc_type, str) and isinstance(summary, str)
        notes.append(Note(path=rel, doc_type=doc_type, summary=summary))
    return notes, problems


@dataclass(frozen=True)
class IndexState:
    """The answer `--check` asks for: is the index what the notes would generate right now?"""

    stale: bool
    problems: list[str]  # notes that cannot be indexed; non-empty means "cannot build at all"
    notes: list[Note]


def index_state(docs_root: Path, registry: Registry, current: str | None = None) -> IndexState:
    """The one implementation of the staleness question.

    Exported so the session hook asks it instead of re-deriving it. Two answers used to differ:
    a note that would not parse read as "not stale" in the hook and "cannot build" in CI, so a
    session was told its index was fine at the moment it was least trustworthy.
    """
    notes, problems = collect(docs_root, registry)
    if problems or not notes:
        return IndexState(stale=True, problems=problems, notes=notes)
    if current is None:
        index = docs_root / registry.settings.index_name
        current = index.read_text(encoding="utf-8") if index.exists() else ""
    return IndexState(stale=current != render(notes), problems=[], notes=notes)


def report_problems(state: IndexState) -> bool:
    """Print why the index cannot be built, if it cannot. True when something was reported."""
    if state.problems:
        print("cannot build the index -- every note needs 'type' and 'summary':", file=sys.stderr)
        for problem in state.problems:
            print(f"  {problem}", file=sys.stderr)
        return True
    if not state.notes:
        print("no notes found -- refusing to write an empty index", file=sys.stderr)
        return True
    return False


def grouped(notes: list[Note]) -> dict[str, list[Note]]:
    """Notes by folder, folders in case-insensitive order, `.` for the top level."""
    groups: dict[str, list[Note]] = {}
    for note in notes:
        groups.setdefault(note.path.parent.as_posix(), []).append(note)
    return {folder: groups[folder] for folder in sorted(groups, key=str.lower)}


def folder_label(folder: str) -> str:
    return "(top level)" if folder == "." else folder


def render(notes: list[Note]) -> str:
    lines = [
        HEADER,
        "",
        "# Documentation index",
        "",
        f"{len(notes)} {plural(len(notes))}, grouped by folder. Regenerate with `doc-marshal index`.",
        "",
    ]
    for folder, members in grouped(notes).items():
        lines += [f"## {folder_label(folder)}", ""]
        for note in members:
            link = quote(note.path.name)
            if folder != ".":
                link = f"{quote(folder)}/{link}"
            lines.append(f"- [{note.path.stem}]({link}) -- `{note.doc_type}` -- {note.summary}")
        lines.append("")
    return "\n".join(lines)


def render_preview(notes: list[Note]) -> str:
    """Folder names with note counts, and nothing else -- the session-start reduction.

    Uniform at every size, top level included (SPEC.md section 7): the full index grows linearly
    with the tree forever, and a summary of every note is a cost every session pays whether or not
    it opens a doc.
    """
    groups = grouped(notes)
    folders = ", ".join(f"{folder_label(folder)} {len(members)}" for folder, members in groups.items())
    return f"{len(notes)} {plural(len(notes))} in {len(groups)} folder(s):\n  {folders}"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        prog="doc-marshal index", description="Regenerate the docs index from every note's frontmatter."
    )
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if the index differs from what would be generated"
    )
    parser.add_argument("--docs-root", help="docs root (default: the directory holding the marker)")
    args = parser.parse_args(argv)

    docs_root = find_docs_root(args.docs_root)
    registry = load_registry(docs_root)
    index = docs_root / registry.settings.index_name

    state = index_state(docs_root, registry)
    if report_problems(state):
        return 1
    notes = state.notes

    if args.check:
        if state.stale:
            print(f"{index.name} is out of date -- regenerate it with `doc-marshal index`", file=sys.stderr)
            return 1
        print(f"{index.name} is up to date -- {len(notes)} {plural(len(notes))}")
        return 0

    index.write_text(render(notes), encoding="utf-8")
    print(f"wrote {index.name} -- {len(notes)} {plural(len(notes))}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
