"""Render every derived copy this repository keeps of what the engine generates.

The policies, the type arguments and marshalling live in the package and are rendered on demand
by `doc-marshal info`, so a user's repository never holds a copy that can go stale. A reviewer on
a pull request cannot run the CLI, though, so this repository keeps one rendering of the standard
profile under `rendered/`, derived from the same source at the same version. The docs tree's own
`CLAUDE.md` and config are `init` output for the same reason and are held to the same source. All
of it is regenerated by the pre-commit hook here and committed back by CI on push to main, which
is what keeps it from being the staleness class the on-demand design removed.

    python scripts/render_doctrine.py          # write rendered/*.md and the docs tree's init files
    python scripts/render_doctrine.py --check  # exit 1 if any derived file differs
"""

from __future__ import annotations

import sys
from pathlib import Path

from doc_marshal import __version__
from doc_marshal.info import render_doc_types, render_marshalling, render_policies
from doc_marshal.init import CONFIG_TEXT, pointer_text
from doc_marshal.ontology import STANDARD
from doc_marshal.settings import SETTINGS

ROOT = Path(__file__).resolve().parent.parent
DOCS = "docs"
HEADER = (
    f"<!-- generated by scripts/render_doctrine.py from doc-marshal {__version__} -- do not edit; "
    "edit src/doc_marshal/doctrine/ and the profile instead -->\n\n"
)


def render() -> dict[str, str]:
    """Every derived file, keyed by its path from the repository root."""
    return {
        "rendered/policies.md": HEADER + render_policies(STANDARD),
        "rendered/doc-types.md": HEADER + render_doc_types(STANDARD),
        "rendered/marshalling.md": HEADER + render_marshalling(),
        f"{DOCS}/CLAUDE.md": pointer_text(DOCS, SETTINGS, STANDARD),
        f"{DOCS}/{SETTINGS.config_name}": CONFIG_TEXT,
    }


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale: list[str] = []
    for name, text in render().items():
        path = ROOT / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if check:
            stale.append(name)
        else:
            path.parent.mkdir(exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if stale:
        print(
            "derived files are out of date: " + ", ".join(stale) + " -- run scripts/render_doctrine.py", file=sys.stderr
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
