"""Render the standard profile's doctrine into `rendered/`, for readers without the CLI.

The policies, the type arguments and marshalling live in the package and are rendered on demand
by `doc-marshal info`, so a user's repository never holds a copy that can go stale. A reviewer on
a pull request cannot run the CLI, though, so this repository keeps one rendering of the standard
profile, derived from the same source at the same version. It is regenerated by the pre-commit
hook here and committed back by CI on push to main, which is what keeps it from being the
staleness class the on-demand design removed.

    python scripts/render_doctrine.py          # write rendered/*.md
    python scripts/render_doctrine.py --check  # exit 1 if any rendered file differs
"""

from __future__ import annotations

import sys
from pathlib import Path

from doc_marshal import __version__
from doc_marshal.info import render_doc_types, render_marshalling, render_policies
from doc_marshal.ontology import STANDARD

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "rendered"
HEADER = (
    f"<!-- generated by scripts/render_doctrine.py from doc-marshal {__version__} -- do not edit; "
    "edit src/doc_marshal/doctrine/ and the profile instead -->\n\n"
)


def render() -> dict[str, str]:
    return {
        "policies.md": HEADER + render_policies(STANDARD),
        "doc-types.md": HEADER + render_doc_types(STANDARD),
        "marshalling.md": HEADER + render_marshalling(),
    }


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale: list[str] = []
    OUT.mkdir(exist_ok=True)
    for name, text in render().items():
        path = OUT / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if check:
            stale.append(name)
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote rendered/{name}")
    if stale:
        print("rendered/ is out of date: " + ", ".join(stale) + " -- run scripts/render_doctrine.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
